// Generated by gencpp from file create_fundamentals/PlaySongRequest.msg
// DO NOT EDIT!


#ifndef CREATE_FUNDAMENTALS_MESSAGE_PLAYSONGREQUEST_H
#define CREATE_FUNDAMENTALS_MESSAGE_PLAYSONGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace create_fundamentals
{
template <class ContainerAllocator>
struct PlaySongRequest_
{
  typedef PlaySongRequest_<ContainerAllocator> Type;

  PlaySongRequest_()
    : number(0)  {
    }
  PlaySongRequest_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef uint8_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlaySongRequest_

typedef ::create_fundamentals::PlaySongRequest_<std::allocator<void> > PlaySongRequest;

typedef boost::shared_ptr< ::create_fundamentals::PlaySongRequest > PlaySongRequestPtr;
typedef boost::shared_ptr< ::create_fundamentals::PlaySongRequest const> PlaySongRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create_fundamentals::PlaySongRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::create_fundamentals::PlaySongRequest_<ContainerAllocator1> & lhs, const ::create_fundamentals::PlaySongRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::create_fundamentals::PlaySongRequest_<ContainerAllocator1> & lhs, const ::create_fundamentals::PlaySongRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace create_fundamentals

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29e94f7568510a2f9241abcc8f191b4f";
  }

  static const char* value(const ::create_fundamentals::PlaySongRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29e94f7568510a2fULL;
  static const uint64_t static_value2 = 0x9241abcc8f191b4fULL;
};

template<class ContainerAllocator>
struct DataType< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create_fundamentals/PlaySongRequest";
  }

  static const char* value(const ::create_fundamentals::PlaySongRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 number\n"
;
  }

  static const char* value(const ::create_fundamentals::PlaySongRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlaySongRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create_fundamentals::PlaySongRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::create_fundamentals::PlaySongRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CREATE_FUNDAMENTALS_MESSAGE_PLAYSONGREQUEST_H
