// Generated by gencpp from file create_fundamentals/ResetEncodersRequest.msg
// DO NOT EDIT!


#ifndef CREATE_FUNDAMENTALS_MESSAGE_RESETENCODERSREQUEST_H
#define CREATE_FUNDAMENTALS_MESSAGE_RESETENCODERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace create_fundamentals
{
template <class ContainerAllocator>
struct ResetEncodersRequest_
{
  typedef ResetEncodersRequest_<ContainerAllocator> Type;

  ResetEncodersRequest_()
    {
    }
  ResetEncodersRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetEncodersRequest_

typedef ::create_fundamentals::ResetEncodersRequest_<std::allocator<void> > ResetEncodersRequest;

typedef boost::shared_ptr< ::create_fundamentals::ResetEncodersRequest > ResetEncodersRequestPtr;
typedef boost::shared_ptr< ::create_fundamentals::ResetEncodersRequest const> ResetEncodersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace create_fundamentals

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create_fundamentals/ResetEncodersRequest";
  }

  static const char* value(const ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetEncodersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::create_fundamentals::ResetEncodersRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CREATE_FUNDAMENTALS_MESSAGE_RESETENCODERSREQUEST_H
